import {
  FilePlus2,
  Split,
  FileSpreadsheet,
  Trash2,
  ArrowUpDown,
  RotateCw,
  FileImage,
  Image,
  Hash,
  Stamp,
  Palette,
  Maximize2,
  Crop,
  FileCode,
  Lock,
  Unlock,
  Images,
  FolderArchive,
  LucideIcon,
} from "lucide-react";

export interface ToolItem {
  id: string;
  title: string;
  description: string;
  href: string;
  icon: LucideIcon;
  iconColor: string;
  iconBg: string;
}

export const PDF_TOOLS: ToolItem[] = [
  {
    id: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs into one file",
    href: "/merge-pdf",
    icon: FilePlus2,
    iconColor: "text-rose-500",
    iconBg: "bg-rose-50",
  },
  {
    id: "split-pdf",
    title: "Split PDF",
    description: "Split PDF into multiple files",
    href: "/split-pdf",
    icon: Split,
    iconColor: "text-blue-500",
    iconBg: "bg-blue-50",
  },
  {
    id: "extract-pages",
    title: "Extract Pages",
    description: "Extract specific pages from PDF",
    href: "/extract-pages",
    icon: FileSpreadsheet,
    iconColor: "text-emerald-500",
    iconBg: "bg-emerald-50",
  },
  {
    id: "delete-pages",
    title: "Delete Pages",
    description: "Remove unwanted pages from PDF",
    href: "/delete-pages",
    icon: Trash2,
    iconColor: "text-amber-600",
    iconBg: "bg-amber-50",
  },
  {
    id: "reorder-pdf",
    title: "Reorder PDF",
    description: "Rearrange PDF pages easily",
    href: "/reorder-pdf",
    icon: ArrowUpDown,
    iconColor: "text-purple-600",
    iconBg: "bg-purple-50",
  },
  {
    id: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate pages in PDF (90°, 180°)",
    href: "/rotate-pdf",
    icon: RotateCw,
    iconColor: "text-amber-500",
    iconBg: "bg-amber-50",
  },
  {
    id: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert PDF pages to JPG images",
    href: "/pdf-to-jpg",
    icon: FileImage,
    iconColor: "text-pink-500",
    iconBg: "bg-pink-50",
  },
  {
    id: "pdf-to-png",
    title: "PDF to PNG",
    description: "Convert PDF pages to PNG images",
    href: "/pdf-to-png",
    icon: FileImage,
    iconColor: "text-cyan-500",
    iconBg: "bg-cyan-50",
  },
  {
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert JPG images to PDF",
    href: "/jpg-to-pdf",
    icon: Image,
    iconColor: "text-indigo-500",
    iconBg: "bg-indigo-50",
  },
  {
    id: "png-to-pdf",
    title: "PNG to PDF",
    description: "Convert PNG images to PDF",
    href: "/png-to-pdf",
    icon: Image,
    iconColor: "text-green-500",
    iconBg: "bg-green-50",
  },
  {
    id: "page-numbering",
    title: "Page Numbering",
    description: "Add page numbers to PDF",
    href: "/page-numbering",
    icon: Hash,
    iconColor: "text-violet-600",
    iconBg: "bg-violet-50",
  },
  {
    id: "watermark-pdf",
    title: "Watermark PDF",
    description: "Add text or image watermark",
    href: "/watermark-pdf",
    icon: Stamp,
    iconColor: "text-sky-500",
    iconBg: "bg-sky-50",
  },
  {
    id: "background-color",
    title: "Background Color",
    description: "Add background color to PDF pages",
    href: "/background-color",
    icon: Palette,
    iconColor: "text-orange-500",
    iconBg: "bg-orange-50",
  },
  {
    id: "page-size-changer",
    title: "Page Size Changer",
    description: "Change PDF page size (A4, Letter, etc.)",
    href: "/page-size-changer",
    icon: Maximize2,
    iconColor: "text-teal-500",
    iconBg: "bg-teal-50",
  },
  {
    id: "crop-pdf",
    title: "Crop PDF",
    description: "Crop PDF pages with custom margins",
    href: "/crop-pdf",
    icon: Crop,
    iconColor: "text-rose-500",
    iconBg: "bg-rose-50",
  },
  {
    id: "pdf-metadata",
    title: "PDF Metadata",
    description: "View and edit PDF metadata",
    href: "/pdf-metadata",
    icon: FileCode,
    iconColor: "text-purple-500",
    iconBg: "bg-purple-50",
  },
  {
    id: "protect-pdf",
    title: "Protect PDF",
    description: "Add password protection to PDF",
    href: "/protect-pdf",
    icon: Lock,
    iconColor: "text-red-500",
    iconBg: "bg-red-50",
  },
  {
    id: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove password from PDF (with password)",
    href: "/unlock-pdf",
    icon: Unlock,
    iconColor: "text-amber-500",
    iconBg: "bg-amber-50",
  },
  {
    id: "extract-images",
    title: "Extract Images",
    description: "Extract images from PDF files",
    href: "/extract-images",
    icon: Images,
    iconColor: "text-blue-500",
    iconBg: "bg-blue-50",
  },
  {
    id: "pdf-to-images-zip",
    title: "PDF to Images (ZIP)",
    description: "Convert all PDF pages to images (ZIP)",
    href: "/pdf-to-images-zip",
    icon: FolderArchive,
    iconColor: "text-emerald-600",
    iconBg: "bg-emerald-50",
  },
];

